server:
  port: 8080

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    generate-dll: true

  datasource:
    url: jdbc:mysql://localhost:3306/order_2_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

