server:
  servlet:
    context-path: /technical-exercise
  port: 8084
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order123_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update
    show-sql: true
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: *********@gmail.com
    password: ******************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

  file:
    path:
    name: myapp.log